### ISSUE TITLE
Add support for Files

### ISSUE THREAD

**Issue by ghost** [manywho/ManyWho_Flow_SDK_Java#11]
We need to support files in the sdk 2.0, the developer should be able to work independent of the framework that is used (in our case reasteasy)

**Comment by jonjo-manywho** [comment]
@jose-manywho could you do a code review on this please? Services just need to have a single implementation of `FileHandler` and the SDK will do the rest of the work for them :)

**Comment by ghost** [comment]
The code looks good to me.
