### ISSUE TITLE
tokens into the RawDatabase methods

### ISSUE THREAD

**Issue by josecollazzi** [manywho/ManyWho_Flow_SDK_Java#25]
I need the AuthenticatedWho.getToken() into the RawDatabase methods, to be able to make a request with the OAuth token of the user.

**Comment by jonjomckay** [comment]
You should be able to inject an `AuthenticatedWhoProvider` into the class, which will give you the correct `AuthenticatedWho` for each request :)

**Comment by josecollazzi** [comment]
👍 cool
