### ISSUE TITLE
When loading objects is not possible to read the list of objects passed by valueElementToReferenceId

### ISSUE THREAD

**Issue by josecollazzi** [manywho/ManyWho_Flow_SDK_Java#34]
When loading a list of objects is not possible to read a list of objects passed by valueElementToReferenceId, this data is camming in the ObjectDataRequest and is accessible by ObjectDataRequest.getObjectData(). 

A new parameter should be added in RawDatabase#findAll and ReadOnlyDatabase#findAll

**Comment by josecollazzi** [comment]
@jonjomckay could you please review?

**Comment by jonjomckay** [comment]
Can you make a PR?
